// Generated by https://quicktype.io

export interface PostEvaResponse {
  acknowledgeId: string;
  dateTime: string;
  operation: string;
  message: string;
  employmentVerificationRequestId: string;
  subscriptionId: string;
  inquiryId: string;
}
