// Generated by https://quicktype.io

export interface UserRiskVerification {
  err: boolean;
  message: string;
  coincidences: number;
  person: Person[];
}

export interface Person {
  id: number;
  person_type: string;
  nombre: string;
  apaterno: string;
  amaterno: string;
  rfc: string;
  curp: string;
  alias: null | string;
  genero: string;
  birthday: string;
  domicilio: string;
  nacionalidad: string;
  observaciones: string;
  pertenece: string;
  actividad: string;
  fecha: null | string;
  tipo: string;
  sueldo_base: string;
  compensacion_garantizada: string;
  total_bruto: string;
  total_neto: string;
  email: string;
  link: string;
  suplente: string;
  pdo_gob_ini: null | string;
  pdo_gob_fin: null | string;
  id_entity: null;
  demands: null;
  porcentaje_coincidencia: string;
  situacion_del_contribuyente: null | string;
  numero_y_fecha_de_oficio_global_de_presuncion: null | string;
  publicacion_pagina_sat_presuntos: null | string;
  publicacion_dof_presuntos: null;
  publicacion_pagina_sat_desvirtuados: null | string;
  numero_fecha_oficio_global_contribuyentes_desvirtuaron: null | string;
  publicacion_dof_desvirtuados: null;
  numero_y_fecha_de_oficio_global_de_definitivos: null | string;
  publicacion_pagina_sat_definitivos: null | string;
  publicacion_dof_definitivos: null;
  numero_y_fecha_de_oficio_global_de_sentencia_favorable: null | string;
  publicacion_pagina_sat_sentencia_favorable: null | string;
  publicacion_dof_sentencia_favorable: null;
  numero_oficio_personas_bloqueadas: string;
  ofac_id: null;
  interpol_id: null;
  facebook: null | string;
  twitter: null | string;
  status: string;
  created_at: string;
  updated_at: null | string;
  photo: string;
  id_product: null;
  id_internal_list: null;
  onu_id: null;
  full_name: string;
  relevancia: string;
}
