// Generated by https://quicktype.io

export interface WeebHookResponse {
  subscriptionId: string;
  eventId: string;
  eventType: string;
  inquiry: Inquiry;
  firstDelivery: string;
  latestDelivery: string;
  dateTime: string;
  deliveryAttempt: number;
}

export interface Inquiry {
  inquiryId: string;
  successCheck: boolean;
  url: string;
}
