// Generated by https://quicktype.io

export interface CreditReport {
  folioConsulta: string;
  folioConsultaOtorgante: string;
  claveOtorgante: string;
  declaracionesConsumidor: string;
  persona: Persona;
  consultas: Consulta[];
  creditos: Credito[];
  domicilios: Domicilio[];
  empleos: Empleo[];
  scores: Score[];
  mensajes: Mensaje[];
}

export interface Consulta {
  fechaConsulta: string;
  claveOtorgante: string;
  nombreOtorgante: string;
  direccionOtorgante: string;
  telefonoOtorgante: string;
  tipoCredito: string;
  claveUnidadMonetaria: string;
  importeCredito: number;
  tipoResponsabilidad: string;
  idDomicilio: string;
  servicios: string;
}

export interface Credito {
  fechaActualizacion?: string;
  registroImpugnado?: number;
  claveOtorgante?: string;
  nombreOtorgante?: string;
  cuentaActual?: string;
  tipoResponsabilidad?: string;
  tipoCuenta?: string;
  tipoCredito?: string;
  claveUnidadMonetaria?: string;
  valorActivoValuacion?: number;
  numeroPagos?: number;
  frecuenciaPagos?: string;
  montoPagar?: number;
  fechaAperturaCuenta?: string;
  fechaUltimoPago?: string;
  fechaUltimaCompra?: string;
  fechaCierreCuenta?: string;
  fechaReporte?: string;
  ultimaFechaSaldoCero?: string;
  garantia?: string;
  creditoMaximo?: number;
  saldoActual?: number;
  limiteCredito?: number;
  saldoVencido?: number;
  numeroPagosVencidos?: number;
  pagoActual?: string;
  historicoPagos?: string;
  fechaRecienteHistoricoPagos?: string;
  fechaAntiguaHistoricoPagos?: string;
  clavePrevencion?: string;
  totalPagosReportados?: number;
  peorAtraso?: number;
  fechaPeorAtraso?: string;
  saldoVencidoPeorAtraso?: number;
  montoUltimoPago?: number;
  idDomicilio?: string;
  servicios?: string;
  CAN?: Can;
}

export interface Can {
  identificadorCAN: string;
  prelacionOrigen: number;
  prelacionActual: number;
  fechaAperturaCAN: string;
  fechaCancelacionCAN: string;
  historicoCAN: string;
  fechaMRCAN: string;
  fechaMACAN: string;
}

export interface Domicilio {
  direccion: string;
  coloniaPoblacion: string;
  delegacionMunicipio: string;
  ciudad: string;
  estado: string;
  CP: string;
  fechaResidencia: string;
  numeroTelefono: string;
  tipoDomicilio: string;
  tipoAsentamiento: string;
  fechaRegistroDomicilio: string;
  tipoAltaDomicilio: number;
  numeroOtorgantesCarga: number;
  numeroOtorgantesConsulta: number;
  idDomicilio: string;
}

export interface Empleo {
  nombreEmpresa: string;
  direccion: string;
  coloniaPoblacion: string;
  delegacionMunicipio: string;
  ciudad: string;
  estado: string;
  CP: string;
  numeroTelefono: string;
  extension: string;
  fax: string;
  puesto: string;
  fechaContratacion: string;
  claveMoneda: string;
  salarioMensual: number;
  fechaUltimoDiaEmpleo: string;
  fechaVerificacionEmpleo: string;
}

export interface Mensaje {
  tipoMensaje: number;
  leyenda: string;
}

export interface Persona {
  apellidoPaterno: string;
  apellidoMaterno: string;
  apellidoAdicional: null;
  nombres: string;
  fechaNacimiento: string;
  RFC: string;
  CURP: string;
  numeroSeguridadSocial: string;
  nacionalidad: string;
  residencia: number;
  estadoCivil: string;
  sexo: string;
  claveElectorIFE: string;
  numeroDependientes: number;
  fechaDefuncion: string;
}

export interface Score {
  nombreScore: string;
  valor: number;
  razones: string[];
}
